### ISSUE TITLE
about download 'small_2_ls_reg.h5'

### ISSUE THREAD

**Issue by AsajuHuishi** [kreshuklab/hylfm-net#2]
Hello, I have tried many times to download 'small_2_ls_reg.h5' during the training process, but all of them failed. Is there any other download link or download method, such as Baidu Cloud?

**Comment by FynnBe** [comment]
Occasionally zenodo.org might be temporarily unavailable. Does it work for you by now?

**Comment by AsajuHuishi** [comment]
Well I've downloaded the beads datasets from zenodo. Now how can I get datasets about medaka Heart  and zebrafish neural 
dynamics?

**Comment by FynnBe** [comment]
The rest of the data will be shared after publication

**Comment by FynnBe** [comment]
> The rest of the data will be shared after publication

see https://github.com/kreshuklab/hylfm-net#data-used-in-paper
